language: generic

# required to install tools on Linux
sudo: required

branches:
  only:
    - develop

addons:
  snaps: hugo

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  verbose: true
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: develop