baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Getting Started with JavaFX"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/openjfx/openjfx-docs/edit/develop/content/"
  description = "Getting Started with JavaFX"
  author = "Abhinay Agarwal"
  themeVariant = "mine"
  # doc constants
  JDK_VERSION = "14"
  JFX_VERSION = "14"
  JFX_GRADLE_PLUGIN = "0.0.8"
  JFX_MAVEN_PLUGIN = "0.0.4"
  JFX_MAVEN_ARCH = "0.0.1"
  JLINK_PLUGIN = "2.12.0"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Getting Started with JavaFX"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> JavaFX GitHub repo"
identifier = "ds"
url = "https://github.com/openjdk/jfx/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> JavaFX Mailing List"
identifier = "mailing-list"
url = "https://mail.openjdk.java.net/mailman/listinfo/openjfx-dev"
weight = 20